---
title: "model-visualizations"
output: html_document
date: "`r Sys.Date()`"
---
```{r, set up, include=FALSE}
library(knitr)
library(tidyverse)
library(odbc)
library(DBI)
library(glue)
library(dplyr)
library(tidyr)
library(dbplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(scales)
library(openxlsx)
library(readxl)
library(rmarkdown)
# set knitr options
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, show = FALSE,
                      message = FALSE, fig.width = 9, fig.height = 5)

# Sinai color scheme
mshs_colors <- c("#221F72", "#00AEFF", "#D80B8C", "#7F7F7F", "#000000", 
                 "#800080", "#FFFF00", "#CC0000", "#38761D", "#F39C12")
```

# Ip Demand
### Bed Charges by Hospital Over Time
```{r hosp bed charges trend}

# trend bed charges (total) over time
run_rate <- baseline %>%
  filter(BILLING_CAT_DESC == 'BED CHARGES') %>%
  group_by(LOC_NAME, SERVICE_DATE) %>%
  summarise(count = n()) %>%
  collect() %>%
  mutate(SERVICE_DATE = as.Date(SERVICE_DATE, "%Y%m%d"))

ggplot(run_rate, aes(x = SERVICE_DATE, y = count, color = LOC_NAME, group = LOC_NAME)) +
  geom_smooth(se = FALSE, method = "loess", span = 0.05, linewidth = 1.2, alpha = 0.9) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_color_manual(values = mshs_colors) +
  labs(
    title = "Bed Charge by Hospital Over Time",
    x = "Service Date",
    y = "Count",
    color = "Hospital"
  ) +
  theme(plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        strip.text = element_text(size = 12, face = "bold"))
```

# IP Utilization
### System Utilization Baseline vs. Scenario
```{r system utilization}
system_utilization <- ip_comparison_daily %>%
  group_by(SERVICE_DATE) %>%
  summarise(CAPACITY_BASELINE = sum(AVG_BED_CAPACITY_BASELINE, na.rm = TRUE),
            CAPACITY_SCENARIO = sum(AVG_BED_CAPACITY_SCENARIO, na.rm = TRUE),
            DEMAND_BASELINE = sum(DAILY_DEMAND_BASELINE, na.rm = TRUE),
            DEMAND_SCENARIO = sum(DAILY_DEMAND_SCENARIO, na.rm = TRUE),
            BASELINE = DEMAND_BASELINE/CAPACITY_BASELINE,
            SCENARIO = DEMAND_SCENARIO/CAPACITY_SCENARIO) %>%
  pivot_longer(cols = c(BASELINE, SCENARIO),
               names_to = "Dataset",
               values_to = "Utilization")


ggplot(system_utilization, aes(x = SERVICE_DATE, y = Utilization, color = Dataset)) +
  geom_smooth(method = "loess", se = FALSE, span = 0.05, linewidth = 1) +
  geom_hline(yintercept = .85, color = "black", linetype = "solid", linewidth = 0.7) +
  scale_y_continuous(labels = scales::percent) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_color_manual(values = mshs_colors) + 
  labs(title = "System Utilization Over Time",
       x = "Service Date",
       y = "Utilization",
       color = "Dataset") +
  theme(plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        strip.text = element_text(size = 12, face = "bold"),
        panel.spacing = unit(1.5, "lines"))
```

### Hospital Utilization Baseline vs. Scenario
```{r hospital utilization}

hospital_utilization <- function(hospital) {
  total_utilization <- ip_comparison_daily %>%
    filter(LOC_NAME == hospital) %>%
  group_by(LOC_NAME, SERVICE_DATE) %>%
  summarise(CAPACITY_BASELINE = sum(AVG_BED_CAPACITY_BASELINE, na.rm = TRUE),
            CAPACITY_SCENARIO = sum(AVG_BED_CAPACITY_SCENARIO, na.rm = TRUE),
            DEMAND_BASELINE = sum(DAILY_DEMAND_BASELINE, na.rm = TRUE),
            DEMAND_SCENARIO = sum(DAILY_DEMAND_SCENARIO, na.rm = TRUE),
            BASELINE = DEMAND_BASELINE/CAPACITY_BASELINE,
            SCENARIO = DEMAND_SCENARIO/CAPACITY_SCENARIO) %>%
  pivot_longer(cols = c(BASELINE, SCENARIO),
               names_to = "Dataset",
               values_to = "Utilization")
  
  plot <- ggplot(total_utilization, aes(x = SERVICE_DATE, y = Utilization, color = Dataset)) +
  geom_smooth(method = "loess", se = FALSE, span = 0.05, linewidth = 1) +
  geom_hline(yintercept = .85, color = "black", linetype = "solid", linewidth = 0.7) +
  scale_y_continuous(labels = scales::percent) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_color_manual(values = mshs_colors) + 
  labs(title = glue("{hospital} Utilization Over Time"),
       x = "Service Date",
       y = "Utilization",
       color = "Dataset") +
  theme(plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        strip.text = element_text(size = 12, face = "bold"),
        panel.spacing = unit(1.5, "lines"))
  
  print(plot)
}

hosps <- unique(ip_comparison_daily$LOC_NAME)

for (hospital in hosps) {
  hospital_utilization(hospital)
}
```

## Baseline vs. Scenario IP Utilization
```{r baseline vs. scenario}

# get list of service groups effected by scenario
service_change <- ip_comparison_total %>%
  filter(AVG_UTILIZATION_BASELINE != AVG_UTILIZATION_SCENARIO) %>%
  ungroup() %>%
  distinct(SERVICE_GROUP) %>%
  pull()

# prep data from graph
results_long <- ip_comparison_monthly %>%
  filter(SERVICE_GROUP %in% service_change) %>%
  pivot_longer(
    cols = c(AVG_UTILIZATION_BASELINE, AVG_UTILIZATION_SCENARIO),
    names_to = "Scenario",
    values_to = "Utilization") %>%
  mutate(
    SERVICE_MONTH = as.Date(SERVICE_MONTH),
    Scenario = case_when(
      Scenario == "AVG_UTILIZATION_BASELINE" ~ "Baseline",
      Scenario == "AVG_UTILIZATION_SCENARIO" ~ "Scenario"),
    Utilization = case_when(
      Scenario == "Scenario" & is.na(Utilization) ~ 1,
      TRUE ~ Utilization))

# Plot
ggplot(results_long, aes(x = SERVICE_MONTH, y = Utilization, fill = Scenario)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_hline(yintercept = .85, color = "black", linetype = "solid", linewidth = 0.7) +
  scale_y_continuous(limits = c(0, 1.5), labels = scales::percent) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_fill_manual(values = mshs_colors) + 
  facet_grid(LOC_NAME ~ SERVICE_GROUP) +
  labs(title = "Inpatient Utilization Comparison",
       x = "Service Month",
       y = "Utilization",
       fill = "Dataset") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
        strip.text = element_text(face = "bold"))
```

## Daily Scenario IP Utilization
```{r scenario utilization}

# Plot
ggplot(ip_comparison_daily %>%
         mutate(SERVICE_DATE = as.Date(SERVICE_DATE)), 
       aes(x = SERVICE_DATE,
           y = UTILIZATION_SCENARIO,
           color = SERVICE_GROUP,
           group = SERVICE_GROUP)
       ) +
geom_smooth(se = FALSE, method = "loess", span = 0.1, linewidth = 1.2) +
geom_hline(yintercept = 0.95, color = "black", linewidth = 1.2) +
facet_wrap(~ LOC_NAME) +
scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1.3)) +
scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
#scale_color_manual(name = "Service Group", values = mshs_colors) +   
labs(
  title = "Daily Utilization (Scenario)",
  x = "Service Date",
  y = "Utilization (Scenario)"
) +
theme_minimal() +
theme(
  legend.position = "bottom",
  plot.title = element_text(hjust = 0.5),
  axis.text.x = element_text(angle = 45, hjust = 1),
  strip.text = element_text(face = "bold"),
  panel.border = element_rect(color = "black", fill = NA)
)
```