---
title: "demo-model"
author: "Greg Lenane"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(odbc)
library(DBI)
library(glue)
library(dplyr)
library(tidyr)
library(dbplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(scales)

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, 
                      message = FALSE, tidy = TRUE,
                      fig.width = 8, fig.height = 5)

# OAO_PRODUCTION DB connection
con_prod <- dbConnect(odbc(), "OAO Cloud DB Production")
# capacity modeling path
cap_dir <- "/SharedDrive/deans/Presidents/SixSigma/Project Based/System/Capacity Modeling/"
```

# Set Scenario Variables
```{r set scenario}

# set hospitals in scenario
hospitals <- list(
  "MSH",
  "MSM"
)

# set of services to be swapped in scenario
services <- list(
  "CARDIOLOGY",
  "CARDIOVASCULAR SURGERY"
)
```

# Baseline Data
```{r read baseline data}

# pull in all encounters and their charges. join with service grouping for IP unit type
baseline_query <- glue(
  "WITH ip AS (
       SELECT *
       FROM MSX_IP_OUTPUT
       WHERE ADMIT_DT_SRC >= DATE '2024-06-01'
         AND ADMIT_DT_SRC <= DATE '2024-12-31'
         AND FACILITY_MSX <> 'MSSN'
   ),
   charge AS (
       select *
       from OE_CHARGE_DETAIL
       where PRIM_ENC_CSN_ID IN (SELECT EPIC_CSN FROM ip)
   ),
   service_group AS (
       select *
       from DASHBD_USER.CLARITY_DEP_REF
   ),
   final as (
   SELECT ip.ENCOUNTER_NO,
          ip.FACILITY_MSX,
          ip.DSCH_DT_SRC,
          ip.DSCH_TIME_SRC,
          ip.ADMIT_DT_SRC,
          ip.ADMIT_TIME_SRC,
          ip.LOS_NO_SRC,
          ip.PRINCIPAL_SURGEON_CD_SRC,
          ip.PRINCIPAL_SURGEON_NAME_MSX,
          ip.MSDRG_CD_SRC,
          ip.MSDRG_DESC_MSX,
          ip.ADMIT_SOURCE_CD_MSX,
          ip.ADMIT_SOURCE_DESC_MSX,
          ip.P_AVG_LOS_MSDRG,
          ip.VERITY_DEPT_CD_SRC,
          ip.VERITY_DEPT_DESC_SRC,
          ip.VERITY_DIV_CD_SRC,
          ip.VERITY_DIV_DESC_SRC,
          charge.FACILITY_ABBR,
          charge.COST_CENTER_C,
          charge.CHARGE_C,
          charge.EPIC_DEPT_ID,
          charge.EPIC_DEPT_NAME,
          charge.QUANTITY,
          charge.SERVICE_DATE,
          charge.CPT_HCPCS_C,
          charge.BILLING_CAT_C,
          charge.BILLING_CAT_DESC,
          charge.RPT_GRP_NINETEEN_C,
          charge.RPT_GRP_NINETEEN_DESC,
          charge.NEW_COST_CENTER_C,
          charge.NEW_GL_COMPONENT,
          service_group.EXTERNAL_NAME,
          service_group.SERVICE_GROUP,
          service_group.RPT_GRP_TWENTYTHREE
   FROM ip
   LEFT JOIN charge
     ON ip.EPIC_CSN = charge.PRIM_ENC_CSN_ID
   LEFT JOIN service_group
     ON charge.EPIC_DEPT_ID = service_group.DEPARTMENT_ID
   ORDER BY ip.EPIC_CSN
   )
   select * from final;")

# create, execute and clear result for MSX IP Charge Desctiptions
baseline_send <- dbSendQuery(con_prod, baseline_query)
baseline <- dbFetch(baseline_send)
dbClearResult(baseline_send)

baseline <- baseline %>%
  mutate(
    FACILITY_MSX = case_when(
      FACILITY_MSX == 'STL' ~ 'MSM',
      FACILITY_MSX == 'RVT' ~ 'MSW',
      FACILITY_MSX == 'BIB' ~ 'MSB',
      FACILITY_MSX == 'BIP' ~ 'MSBI',
      TRUE ~ FACILITY_MSX))

# read in bed capacity (tableau)
# List all CSV files in the directory
bed_cap_csv <- list.files(paste0(cap_dir, "Tableau Data/Bed Capacity/"),
                          pattern = "\\.csv$", full.names = TRUE)
bed_cap <- bed_cap_csv %>%
  map_dfr(~ read_csv(.x) %>% mutate(source_file = basename(.x))) %>%
  rename(HOSPITAL = Location,
         SERVICE_GROUP = `Service Group`,
         MEASURE = `Measure Names`,
         SERVICE_MONTH = `Day of Census Start`) %>%
  filter(MEASURE == 'Avg Total Beds') %>%
  mutate(
    HOSPITAL = case_when(
      HOSPITAL == "MOUNT SINAI BETH ISRAEL" ~ "MSBI",
      HOSPITAL == "MOUNT SINAI BROOKLYN" ~ "MSB",
      HOSPITAL == "MOUNT SINAI MORNINGSIDE" ~ "MSM",
      HOSPITAL == "MOUNT SINAI QUEENS" ~ "MSQ",
      HOSPITAL == "MOUNT SINAI WEST" ~ "MSW",
      HOSPITAL == "THE MOUNT SINAI HOSPITAL" ~ "MSH"),
    SERVICE_MONTH = mdy(SERVICE_MONTH)) %>%
  group_by(HOSPITAL, SERVICE_GROUP, SERVICE_MONTH) %>%
  summarise(AVG_BED_CAPACITY = sum(`Measure Values`, na.rm = TRUE))
```

# Scenario Data
```{r scenario data}

# create new dummy hospital column to represent new location for scenario population
scenario <- baseline %>%
  mutate(
    FACILITY_MSX = case_when(
      FACILITY_MSX == hospitals[[1]] & VERITY_DEPT_DESC_SRC == services[[2]] ~ "MSM",
      FACILITY_MSX == hospitals[[2]] & VERITY_DEPT_DESC_SRC == services[[1]] ~ "MSH",
      TRUE ~ FACILITY_MSX))
```

# Data Processing
```{r data processing}

# place datasets in list to iterate through
datasets <- list(
  "baseline" = baseline,
  "scenario" = scenario
)

# remove original dataframes to free up space
rm(baseline, scenario)

# filter data down to IP bed charges in desired date range
datasets_processed <- lapply(datasets, function(df) {
  df %>%
    filter(!is.na(EXTERNAL_NAME),
           BILLING_CAT_DESC == "BED CHARGES") %>%
    mutate(
      SERVICE_DATE = as.Date(paste0(
        substr(SERVICE_DATE, 1, 4), "-",
        substr(SERVICE_DATE, 5, 6), "-",
        substr(SERVICE_DATE, 7, 8))),
      SERVICE_MONTH = floor_date(SERVICE_DATE, unit = "month"),
      MONTH_DAYS = days_in_month(SERVICE_MONTH)) %>%
    filter(SERVICE_DATE <= as.Date("2024-12-31"))
})
```

# Capacity, Demand & Utilization
```{r visualize bed demand}

# calculate daily statistics for each hospital and unit type
demand_capacity <- lapply(datasets_processed, function(df) {
  df %>%
    group_by(FACILITY_MSX, SERVICE_GROUP, SERVICE_MONTH, MONTH_DAYS, SERVICE_DATE) %>%
    summarise(DAILY_DEMAND = sum(QUANTITY), .groups = "drop") %>%
    left_join(bed_cap, by = c("FACILITY_MSX" = "HOSPITAL", 
                              "SERVICE_GROUP" = "SERVICE_GROUP",
                              "SERVICE_MONTH" = "SERVICE_MONTH")) %>%
    mutate(UTILIZATION = DAILY_DEMAND/AVG_BED_CAPACITY)
})
```

# Scenario Outputs
### Demand & Utilization Comparison
```{r}

# compare utilization of baseline and scenario at daily level
results_comparison_daily <- demand_capacity[["baseline"]] %>%
  full_join(demand_capacity[["scenario"]],
            by = c("FACILITY_MSX"="FACILITY_MSX",
                   "SERVICE_GROUP"="SERVICE_GROUP",
                   "SERVICE_MONTH"="SERVICE_MONTH",
                   "SERVICE_DATE"="SERVICE_DATE",
                   "AVG_BED_CAPACITY"="AVG_BED_CAPACITY"),
            suffix = c("_BASELINE", "_SCENARIO")) %>%
  filter(FACILITY_MSX %in% hospitals)

# aggregate comparison at monthly level
results_comparison_monthly <- results_comparison_daily %>%
  group_by(FACILITY_MSX, SERVICE_GROUP, SERVICE_MONTH, AVG_BED_CAPACITY) %>%
  summarise(AVG_DAILY_DEMAND_BASELINE = mean(DAILY_DEMAND_BASELINE),
            AVG_DAILY_DEMAND_SCENARIO = mean(DAILY_DEMAND_SCENARIO),
            AVG_UTILIZATION_BASELINE = mean(UTILIZATION_BASELINE),
            AVG_UTILIZATION_SCENARIO = mean(UTILIZATION_SCENARIO)) %>%
  mutate(across(where(is.numeric), \(x) coalesce(x, 0))) %>%
  mutate(AVG_UTILIZATION_SCENARIO = if_else(AVG_UTILIZATION_SCENARIO == 0, Inf, AVG_UTILIZATION_SCENARIO))

# aggregate comparison at total level
results_comparison_total <- results_comparison_monthly %>%
  group_by(FACILITY_MSX, SERVICE_GROUP) %>% 
  summarise(AVG_DAILY_DEMAND_BASELINE = mean(AVG_DAILY_DEMAND_BASELINE),
            AVG_DAILY_DEMAND_SCENARIO = mean(AVG_DAILY_DEMAND_SCENARIO),
            AVG_UTILIZATION_BASELINE =  mean(AVG_UTILIZATION_BASELINE),
            AVG_UTILIZATION_SCENARIO =  mean(AVG_UTILIZATION_SCENARIO),
            AVG_BED_CAPACITY = mean(AVG_BED_CAPACITY),
            AVG_VARIANCE_BASELINE = AVG_DAILY_DEMAND_BASELINE - AVG_BED_CAPACITY,
            AVG_VARIANCE_SCENARIO = AVG_DAILY_DEMAND_SCENARIO - AVG_BED_CAPACITY)
``` 

### Utilization Output
```{r utilization output}

# create table for output
utilization_output <- results_comparison_total %>%
  pivot_wider(id_cols = SERVICE_GROUP,
              names_from = FACILITY_MSX,
              values_from = c(AVG_BED_CAPACITY,
                              AVG_DAILY_DEMAND_BASELINE,
                              AVG_DAILY_DEMAND_SCENARIO,
                              AVG_UTILIZATION_BASELINE,
                              AVG_UTILIZATION_SCENARIO,
                              AVG_VARIANCE_BASELINE,
                              AVG_VARIANCE_SCENARIO)) %>%
  select(SERVICE_GROUP, contains(hospitals[[1]]), contains(hospitals[[2]]))

writexl::write_xlsx(utilization_output, paste0(cap_dir, "Model Outputs/Utilization/util_",
                                               hospitals[[1]], services[[1]], "-",
                                               hospitals[[2]], services[[2]], ".xlsx"))
```

### Visualizations
#### Baseline vs. Scenario Utilization
```{r baseline vs. scenario}

# get list of service groups effected by scenario
service_change <- results_comparison_total %>%
  filter(AVG_UTILIZATION_BASELINE != AVG_UTILIZATION_SCENARIO) %>%
  ungroup() %>%
  distinct(SERVICE_GROUP) %>%
  pull()

# prep data from graph
results_long <- results_comparison_monthly %>%
  filter(SERVICE_GROUP %in% service_change) %>%
  pivot_longer(
    cols = c(AVG_UTILIZATION_BASELINE, AVG_UTILIZATION_SCENARIO),
    names_to = "Scenario",
    values_to = "Utilization") %>%
  mutate(
    Scenario = case_when(
      Scenario == "AVG_UTILIZATION_BASELINE" ~ "Baseline",
      Scenario == "AVG_UTILIZATION_SCENARIO" ~ "Scenario"),
    # dummy 95% utilization for services introduced by scenario
    Utilization = case_when(
      Scenario == "Scenario" & is.na(Utilization) ~ 1,
      TRUE ~ Utilization))

# Plot
ggplot(results_long, aes(x = SERVICE_MONTH, y = Utilization, fill = Scenario)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_hline(yintercept = .95, color = "black", linetype = "solid", linewidth = 0.7) +
  scale_y_continuous(limits = c(0, 1.5), labels = scales::percent) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  facet_grid(FACILITY_MSX ~ SERVICE_GROUP) +
  labs(title = "Utilization Comparison",
       x = "Service Month",
       y = "Utilization",
       fill = "Scenario") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
  panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    strip.text = element_text(face = "bold"))
```

#### Daily Scenario Utilization
```{r utilization over time}

# Plot
ggplot(results_comparison_daily, aes(
  x = SERVICE_DATE,
  y = UTILIZATION_SCENARIO,
  color = SERVICE_GROUP,
  group = SERVICE_GROUP,
  text = paste0("Service Group: ", SERVICE_GROUP,
                "<br>Utilization: ", round(UTILIZATION_SCENARIO * 100, 1), "%"))
) +
geom_smooth(se = FALSE, method = "loess", span = 0.2, linewidth = 1.2) +
geom_hline(yintercept = 0.95, color = "black", linewidth = 1.2) +
facet_wrap(~ FACILITY_MSX) +
scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1.3)) +
scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
scale_color_discrete(name = "Service Group") +
labs(
  title = "Utilization Over Time",
  x = "Service Date",
  y = "Utilization (Scenario)"
) +
theme_minimal() +
theme(
  legend.position = "bottom",
  axis.text.x = element_text(angle = 45, hjust = 1),
  strip.text = element_text(face = "bold"),
  panel.border = element_rect(color = "black", fill = NA)
)



```

#### Unit Type Demand for Scenario
```{r unit type demand}

# this plot answers question of, in the scenario situation what would be the unit type demand for the scenario group
# filter down data needed for plot
unit_type_demand <- datasets_processed[["scenario"]] %>%
  filter(FACILITY_MSX %in% hospitals,
         VERITY_DEPT_DESC_SRC %in% services)

# define facet labels
facility_labels <- setNames(paste(hospitals, "-", services),hospitals)

ggplot(unit_type_demand, aes(x = SERVICE_GROUP)) +
  geom_bar(fill = "steelblue") +  
  geom_text(
    stat = "count",
    aes(label = after_stat(count)),
    vjust = -0.5,
    size = 3) +
  facet_wrap(~ FACILITY_MSX,
             labeller = labeller(FACILITY_MSX = facility_labels)) + 
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.1))) +
  labs(
   x = "Service Group",
   y = "Count",
   title = "Count of Unit Type by Scenario") +
  theme(
   axis.text.x = element_text(angle = 45, hjust = 1),
   panel.border = element_rect(color = "black", fill = NA, size = 1))
```


# Quality Checks
### Epic Encounter Check
```{r encounter check}
msx_encounters <- glue(
  "SELECT DISTINCT EPIC_CSN
   FROM MSX_IP_OUTPUT
   WHERE ADMIT_DT_SRC >= DATE '2024-01-01' AND 
         ADMIT_DT_SRC <= DATE '2024-12-31' AND 
         FACILITY_MSX <> 'MSSN';")

oe_encounters <- glue(
  "WITH ip AS (
       SELECT *
       FROM MSX_IP_OUTPUT
       WHERE ADMIT_DT_SRC >= DATE '2024-01-01'
         AND ADMIT_DT_SRC <= DATE '2024-12-31'
         AND FACILITY_MSX <> 'MSSN'
   ),
   charge AS (
       select *
       from OE_CHARGE_DETAIL
       where PRIM_ENC_CSN_ID IN (SELECT EPIC_CSN FROM ip))
  select distinct PRIM_ENC_CSN_ID from charge"
)

# create, execute and clear result for MSX IP Encounters
msx_send <- dbSendQuery(con_prod, msx_encounters)
msx <- dbFetch(msx_send)
dbClearResult(msx_send)

# create, execute and clear result for MSX IP Encounters
oe_send <- dbSendQuery(con_prod, oe_encounters)
oe <- dbFetch(oe_send)
dbClearResult(oe_send)

percent_of_encounters <- 
  (length(msx$EPIC_CSN) - length(setdiff(msx$EPIC_CSN, oe$PRIM_ENC_CSN_ID)))/length(msx$EPIC_CSN) 

print(percent_of_encounters)

```

### Bed Charges Over Time
```{r bed charges trend}
query <- glue(
  "WITH ip AS (
       SELECT *
       FROM MSX_IP_OUTPUT
       WHERE ADMIT_DT_SRC >= DATE '2024-01-01' AND 
             FACILITY_MSX <> 'MSSN'
   ),
   charge AS (
       select *
       from OE_CHARGE_DETAIL
       where PRIM_ENC_CSN_ID IN (SELECT EPIC_CSN FROM ip) AND
             BILLING_CAT_DESC = 'BED CHARGES'
   )
   select SERVICE_DATE from charge;"
)

# create, execute and clear result for MSX IP Charge Desctiptions
send <- dbSendQuery(con_prod, query)
datacheck <- dbFetch(send)
dbClearResult(send)

test <- datacheck %>%
  mutate(SERVICE_DATE = as.Date(paste0(
    substr(SERVICE_DATE, 1, 4), "-",
    substr(SERVICE_DATE, 5, 6), "-",
    substr(SERVICE_DATE, 7, 8)))) %>%
  group_by(SERVICE_DATE) %>%
  summarise(count = n())

ggplot(test, aes(x = SERVICE_DATE, y = count)) +
  geom_line(color = "steelblue", linewidth = 1) +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b %Y"  # e.g., Jan 2025
  ) +
  labs(
    title = "Bed Charge Count Over Time",
    x = "Service Date",
    y = "Count"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```





