---
title: "model-lab-rad"
output: html_document
date: "`r Sys.Date()`"
---

# Read Processing
```{r dataset list}
# read in bed capacity (tableau)
# List all CSV files in the directory
bed_cap_csv <- list.files(paste0(cap_dir, "Tableau Data/Bed Capacity/"),
                          pattern = "\\.csv$", full.names = TRUE)
bed_cap <- bed_cap_csv %>%
  map_dfr(~ read_csv(.x) %>% mutate(source_file = basename(.x))) %>%
  rename(HOSPITAL = Location,
         SERVICE_GROUP = `Service Group`,
         MEASURE = `Measure Names`,
         SERVICE_MONTH = `Day of Census Start`) %>%
  filter(MEASURE == 'Avg Total Beds') %>%
  mutate(
    HOSPITAL = case_when(
      HOSPITAL == "MOUNT SINAI BETH ISRAEL" ~ "MSBI",
      HOSPITAL == "MOUNT SINAI BROOKLYN" ~ "MSB",
      HOSPITAL == "MOUNT SINAI MORNINGSIDE" ~ "MSM",
      HOSPITAL == "MOUNT SINAI QUEENS" ~ "MSQ",
      HOSPITAL == "MOUNT SINAI WEST" ~ "MSW",
      HOSPITAL == "THE MOUNT SINAI HOSPITAL" ~ "MSH"),
    SERVICE_MONTH = mdy(SERVICE_MONTH)) %>%
  group_by(HOSPITAL, SERVICE_GROUP, SERVICE_MONTH) %>%
  summarise(AVG_BED_CAPACITY = sum(`Measure Values`, na.rm = TRUE))

# read in processed data from data refresh script
datasets_processed <- list(
  "baseline" = tbl(con_prod, "IPCAP_PROCESSED_DATA") %>%
    mutate(
      SERVICE_DATE = TO_DATE(SERVICE_DATE, 'YYYYMMDD'),
      SERVICE_MONTH = sql("TRUNC(TO_DATE(SERVICE_DATE, 'YYYYMMDD'), 'MM')"),
      FACILITY_MSX = case_when(
        FACILITY_MSX == 'STL' ~ 'MSM',
        FACILITY_MSX == 'RVT' ~ 'MSW',
        FACILITY_MSX == 'BIB' ~ 'MSB',
        FACILITY_MSX == 'BIP' ~ 'MSBI',
        TRUE ~ FACILITY_MSX)),
  "scenario" = tbl(con_prod, "IPCAP_PROCESSED_DATA") %>%
    mutate(
      SERVICE_DATE = TO_DATE(SERVICE_DATE, 'YYYYMMDD'),
      SERVICE_MONTH = sql("TRUNC(TO_DATE(SERVICE_DATE, 'YYYYMMDD'), 'MM')"),
      FACILITY_MSX = case_when(
        FACILITY_MSX == 'STL' ~ 'MSM',
        FACILITY_MSX == 'RVT' ~ 'MSW',
        FACILITY_MSX == 'BIB' ~ 'MSB',
        FACILITY_MSX == 'BIP' ~ 'MSBI',
        TRUE ~ FACILITY_MSX),
      FACILITY_MSX = case_when(
        FACILITY_MSX == local(hospitals[[1]]) & VERITY_DEPT_DESC_SRC == local(services[[2]]) ~ "MSM",
        FACILITY_MSX == local(hospitals[[2]]) & VERITY_DEPT_DESC_SRC == local(services[[1]]) ~ "MSH",
        TRUE ~ FACILITY_MSX)))
```


## Lab & Radiology Demand
```{r lab & radiology demand}

# hospitals vector
hospitals_vec <- unlist(hospitals)

# lab demand
lab_demand <- list()
for (i in 1:length(datasets_processed)) {
  lab_demand[[i]] <- datasets_processed[[i]] %>%
    filter(FACILITY_MSX %in% hospitals_vec) %>%
    filter(LAB_COUNT == 1) %>%
    group_by(FACILITY_MSX, SERVICE_MONTH, SERVICE_DATE, CPT_HCPCS_C, DESCRIPTION_SHORT) %>%
    summarise(DEMAND = sum(QUANTITY)) %>%
    collect() %>%
    mutate(CATEGORY = "LAB",
           DATASET = names(datasets_processed)[i])
  names(lab_demand)[i] <- names(datasets_processed)[i]
}

# rad demand
rad_demand <- list()
for (i in 1:length(datasets_processed)) {
  rad_demand[[i]] <- datasets_processed[[i]] %>%
    filter(FACILITY_MSX %in% hospitals_vec,
           CATEGORY == "RAD",
           CPT_COUNT == 1) %>%
    group_by(FACILITY_MSX, SERVICE_MONTH, SERVICE_DATE, CPT_HCPCS_C, DESCRIPTION_SHORT) %>%
    summarise(DEMAND = sum(QUANTITY)) %>%
    collect() %>%
    mutate(CATEGORY = "RAD",
           DATASET = names(datasets_processed)[i])
  names(rad_demand)[i] <- names(datasets_processed)[i]
}

# comparison of average lab/rad charges for all baseline verity departments
lab_baseline_comp <- datasets_processed[["baseline"]] %>%
  filter(FACILITY_MSX %in% hospitals_vec,
         LAB_COUNT == 1) %>%
  group_by(FACILITY_MSX, VERITY_DEPT_DESC_SRC, ENCOUNTER_NO) %>%
  summarise(SUM_LAB = sum(QUANTITY)) %>%
  group_by(FACILITY_MSX, VERITY_DEPT_DESC_SRC) %>%
  summarise(AVG_LAB = mean(SUM_LAB)) %>%
  arrange(VERITY_DEPT_DESC_SRC) %>%
  collect()

# comparison
rad_baseline_comp <- datasets_processed[["baseline"]] %>%
  filter(FACILITY_MSX %in% hospitals_vec,
         CATEGORY == "RAD",
         CPT_COUNT == 1) %>%
  group_by(FACILITY_MSX, VERITY_DEPT_DESC_SRC, ENCOUNTER_NO) %>%
  summarise(SUM_RAD = sum(QUANTITY)) %>%
  group_by(FACILITY_MSX, VERITY_DEPT_DESC_SRC) %>%
  summarise(AVG_RAD = mean(SUM_RAD)) %>%
  arrange(VERITY_DEPT_DESC_SRC) %>%
  collect()

# combine all and remove individual dfs
lab_rad_demand <- rbind(
  lab_demand[["baseline"]],
  lab_demand[["scenario"]],
  rad_demand[["baseline"]],
  rad_demand[["scenario"]]
)

rm(lab_demand, rad_demand)
```

# Scenario Outputs
## Lab & Rad Scenario Comparison
```{r lab & rad scenario comparison}

# create table for output
lab_rad_output <- lab_rad_demand %>%
  filter(FACILITY_MSX %in% hospitals) %>%
  group_by(FACILITY_MSX, SERVICE_MONTH, CATEGORY, DATASET) %>%
  summarise(DEMAND = sum(DEMAND)) %>%
  pivot_wider(id_cols = c(FACILITY_MSX, SERVICE_MONTH, CATEGORY),
              names_from = DATASET,
              values_from = DEMAND) %>%
  mutate(PERCENT_CHANGE = (scenario - baseline)/baseline,
         COUNT_BASELINE = baseline,
         COUNT_SCENARIO = scenario) %>%
  pivot_wider(id_cols = SERVICE_MONTH,
              names_from = c(CATEGORY, FACILITY_MSX),
              values_from = c(COUNT_BASELINE, 
                              COUNT_SCENARIO,
                              PERCENT_CHANGE)) %>%
  select(SERVICE_MONTH, contains("LAB"), contains("RAD")) %>%
  select(SERVICE_MONTH, contains(hospitals[[1]]), contains(hospitals[[2]]))

```

## Lab & Rad Baseline Comparison
```{r lab & rad baseline comparison}

# create table for output
lab_rad_baseline_comp <- lab_baseline_comp %>%
  left_join(rad_baseline_comp, by = c("FACILITY_MSX"="FACILITY_MSX",
                                     "VERITY_DEPT_DESC_SRC"="VERITY_DEPT_DESC_SRC"))
```

# Visualizations
## Daily Lab Demand
```{r lab daily trend}

# data
results_lab <- lab_rad_demand %>%
  filter(FACILITY_MSX %in% hospitals,
         CATEGORY == "LAB") %>%
  group_by(FACILITY_MSX, SERVICE_DATE, DATASET) %>%
  summarise(DEMAND = sum(DEMAND)) %>%
  mutate(SERVICE_DATE = as.Date(SERVICE_DATE))

# visualization
ggplot(results_lab, aes(x = SERVICE_DATE, y = DEMAND, color = DATASET, group = DATASET)) +
  geom_smooth(se = FALSE, method = "loess", span = 0.1, linewidth = 1.2, alpha = 0.9) +
  facet_grid(~ FACILITY_MSX, scales = "free_y") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_color_manual(values = mshs_colors) +
  labs(
    title = "Baseline vs. Scenario Lab Demand",
    x = "Date",
    y = "Demand",
    color = "Dataset"
  ) +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        strip.text = element_text(size = 14, face = "bold"))
```

## Daily Radiology Demand
```{r rad daily trend}

# data
results_rad <- lab_rad_demand %>%
  filter(FACILITY_MSX %in% hospitals,
         CATEGORY == "RAD") %>%
  group_by(FACILITY_MSX, SERVICE_DATE, DATASET) %>%
  summarise(DEMAND = sum(DEMAND)) %>%
  mutate(SERVICE_DATE = as.Date(SERVICE_DATE))

# visualization
ggplot(results_rad, aes(x = SERVICE_DATE, y = DEMAND, color = DATASET, group = DATASET)) +
  geom_smooth(se = FALSE, method = "loess", span = 0.1, linewidth = 1.2, alpha = 0.9) +
  facet_grid(~ FACILITY_MSX, scales = "free_y") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_color_manual(values = mshs_colors) +
  labs(
    title = "Baseline vs. Scenario Radiology Demand",
    x = "Date",
    y = "Demand",
    color = "Dataset"
  ) +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        strip.text = element_text(size = 14, face = "bold"))
```