---
title: "model-ip-utilization"
output: html_document
date: "`r Sys.Date()`"
---

# Read Processing
```{r dataset list}
# read in bed capacity (tableau)
# List all CSV files in the directory
bed_cap_csv <- list.files(paste0(cap_dir, "Tableau Data/Bed Capacity/"),
                          pattern = "\\.csv$", full.names = TRUE)
bed_cap <- bed_cap_csv %>%
  map_dfr(~ read_csv(.x) %>% mutate(source_file = basename(.x))) %>%
  rename(HOSPITAL = Location,
         SERVICE_GROUP = `Service Group`,
         MEASURE = `Measure Names`,
         SERVICE_MONTH = `Day of Census Start`) %>%
  filter(MEASURE == 'Avg Total Beds') %>%
  mutate(
    HOSPITAL = case_when(
      HOSPITAL == "MOUNT SINAI BETH ISRAEL" ~ "MSBI",
      HOSPITAL == "MOUNT SINAI BROOKLYN" ~ "MSB",
      HOSPITAL == "MOUNT SINAI MORNINGSIDE" ~ "MSM",
      HOSPITAL == "MOUNT SINAI QUEENS" ~ "MSQ",
      HOSPITAL == "MOUNT SINAI WEST" ~ "MSW",
      HOSPITAL == "THE MOUNT SINAI HOSPITAL" ~ "MSH"),
    SERVICE_MONTH = mdy(SERVICE_MONTH)) %>%
  group_by(HOSPITAL, SERVICE_GROUP, SERVICE_MONTH) %>%
  summarise(AVG_BED_CAPACITY = sum(`Measure Values`, na.rm = TRUE))

# read in processed data from data refresh script
datasets_processed <- list(
  "baseline" = tbl(con_prod, "IPCAP_PROCESSED_DATA") %>%
    mutate(
      SERVICE_DATE = TO_DATE(SERVICE_DATE, 'YYYYMMDD'),
      SERVICE_MONTH = sql("TRUNC(TO_DATE(SERVICE_DATE, 'YYYYMMDD'), 'MM')"),
      FACILITY_MSX = case_when(
        FACILITY_MSX == 'STL' ~ 'MSM',
        FACILITY_MSX == 'RVT' ~ 'MSW',
        FACILITY_MSX == 'BIB' ~ 'MSB',
        FACILITY_MSX == 'BIP' ~ 'MSBI',
        TRUE ~ FACILITY_MSX)),
  "scenario" = tbl(con_prod, "IPCAP_PROCESSED_DATA") %>%
    mutate(
      SERVICE_DATE = TO_DATE(SERVICE_DATE, 'YYYYMMDD'),
      SERVICE_MONTH = sql("TRUNC(TO_DATE(SERVICE_DATE, 'YYYYMMDD'), 'MM')"),
      FACILITY_MSX = case_when(
        FACILITY_MSX == 'STL' ~ 'MSM',
        FACILITY_MSX == 'RVT' ~ 'MSW',
        FACILITY_MSX == 'BIB' ~ 'MSB',
        FACILITY_MSX == 'BIP' ~ 'MSBI',
        TRUE ~ FACILITY_MSX),
      FACILITY_MSX = case_when(
        FACILITY_MSX == local(hospitals[[1]]) & VERITY_DEPT_DESC_SRC == local(services[[2]]) ~ "MSM",
        FACILITY_MSX == local(hospitals[[2]]) & VERITY_DEPT_DESC_SRC == local(services[[1]]) ~ "MSH",
        TRUE ~ FACILITY_MSX)))
```

## IP Demand & Utilization
```{r ip}

# get billing descripions for IP categories
ip_mapping <- tbl(con_prod, "IPCAP_BILLING_CAT_DESC") %>%
  filter(CATEGORY == "IP") %>%
  collect() %>%
  pull(BILLING_CAT_DESC)

# filter data down to IP bed charges in desired date range
ip_utilization <- lapply(datasets_processed, function(df) {
  df %>%
    filter(!is.na(EXTERNAL_NAME),
           BILLING_CAT_DESC == ip_mapping) %>%
    group_by(FACILITY_MSX, SERVICE_GROUP, SERVICE_MONTH, SERVICE_DATE) %>%
    summarise(DAILY_DEMAND = sum(QUANTITY), .groups = "drop") %>%
    collect() %>%
    left_join(bed_cap, by = c("FACILITY_MSX" = "HOSPITAL", 
                              "SERVICE_GROUP" = "SERVICE_GROUP",
                              "SERVICE_MONTH" = "SERVICE_MONTH")) %>%
    mutate(UTILIZATION = DAILY_DEMAND/AVG_BED_CAPACITY,
           UTILIZATION_90 = case_when(
             UTILIZATION > .90 ~ TRUE,
             TRUE ~ FALSE),
           UTILIZATION_95 = case_when(
             UTILIZATION > .95 ~ TRUE,
             TRUE ~ FALSE))
})
```

# Scenario Outputs
## IP Demand & Utilization Comparison
```{r ip comparison}

# compare utilization of baseline and scenario at daily level
ip_comparison_daily <- ip_utilization[["baseline"]] %>%
  full_join(ip_utilization[["scenario"]],
            by = c("FACILITY_MSX"="FACILITY_MSX",
                   "SERVICE_GROUP"="SERVICE_GROUP",
                   "SERVICE_MONTH"="SERVICE_MONTH",
                   "SERVICE_DATE"="SERVICE_DATE",
                   "AVG_BED_CAPACITY"="AVG_BED_CAPACITY"),
            suffix = c("_BASELINE", "_SCENARIO")) %>%
  filter(FACILITY_MSX %in% hospitals)

# aggregate comparison at monthly level
ip_comparison_monthly <- ip_comparison_daily %>%
  group_by(FACILITY_MSX, SERVICE_GROUP, SERVICE_MONTH, AVG_BED_CAPACITY) %>%
  summarise(AVG_DAILY_DEMAND_BASELINE = mean(DAILY_DEMAND_BASELINE),
            AVG_DAILY_DEMAND_SCENARIO = mean(DAILY_DEMAND_SCENARIO),
            AVG_UTILIZATION_BASELINE = mean(UTILIZATION_BASELINE),
            AVG_UTILIZATION_SCENARIO = mean(UTILIZATION_SCENARIO),
            PERCENT_90_BASELINE = mean(UTILIZATION_90_BASELINE),
            PERCENT_90_SCENARIO = mean(UTILIZATION_90_SCENARIO),
            PERCENT_95_BASELINE = mean(UTILIZATION_95_BASELINE),
            PERCENT_95_SCENARIO = mean(UTILIZATION_95_SCENARIO)) %>%
  mutate(across(where(is.numeric), \(x) coalesce(x, 0))) %>%
  mutate(AVG_UTILIZATION_SCENARIO = if_else(AVG_UTILIZATION_SCENARIO == 0, Inf, AVG_UTILIZATION_SCENARIO))

# aggregate comparison at total level
ip_comparison_total <- ip_comparison_monthly %>%
  group_by(FACILITY_MSX, SERVICE_GROUP) %>% 
  summarise(AVG_DAILY_DEMAND_BASELINE = mean(AVG_DAILY_DEMAND_BASELINE),
            AVG_DAILY_DEMAND_SCENARIO = mean(AVG_DAILY_DEMAND_SCENARIO),
            AVG_UTILIZATION_BASELINE =  mean(AVG_UTILIZATION_BASELINE),
            AVG_UTILIZATION_SCENARIO =  mean(AVG_UTILIZATION_SCENARIO),
            AVG_PERCENT90_BASELINE = mean(PERCENT_90_BASELINE),
            AVG_PERCENT90_SCENARIO = mean(PERCENT_90_SCENARIO),
            AVG_PERCENT95_BASELINE = mean(PERCENT_95_BASELINE),
            AVG_PERCENT95_SCENARIO = mean(PERCENT_95_SCENARIO),
            AVG_BED_CAPACITY = mean(AVG_BED_CAPACITY),
            AVG_VARIANCE_BASELINE = AVG_DAILY_DEMAND_BASELINE - AVG_BED_CAPACITY,
            AVG_VARIANCE_SCENARIO = AVG_DAILY_DEMAND_SCENARIO - AVG_BED_CAPACITY)

rm(ip_utilization)
``` 

## IP Utilization Output
```{r utilization output}

# create table for output
ip_utilization_output <- ip_comparison_total %>%
  pivot_wider(id_cols = SERVICE_GROUP,
              names_from = FACILITY_MSX,
              values_from = c(AVG_BED_CAPACITY,
                              AVG_DAILY_DEMAND_BASELINE,
                              AVG_DAILY_DEMAND_SCENARIO,
                              AVG_UTILIZATION_BASELINE,
                              AVG_UTILIZATION_SCENARIO,
                              AVG_PERCENT90_BASELINE,
                              AVG_PERCENT90_SCENARIO,
                              AVG_PERCENT95_BASELINE,
                              AVG_PERCENT95_SCENARIO,
                              AVG_VARIANCE_BASELINE,
                              AVG_VARIANCE_SCENARIO)) %>%
  select(SERVICE_GROUP, contains(hospitals[[1]]), contains(hospitals[[2]])) 
```

# Visualizations
## Total Utilization Baseline vs. Scenario
```{r total utilization}
total_utilization <- ip_comparison_daily %>%
  group_by(FACILITY_MSX, SERVICE_DATE) %>%
  summarise(BASELINE = sum(DAILY_DEMAND_BASELINE, na.rm = TRUE)/sum(AVG_BED_CAPACITY, na.rm = TRUE),
            SCENARIO = sum(DAILY_DEMAND_SCENARIO, na.rm = TRUE)/sum(AVG_BED_CAPACITY, na.rm = TRUE)) %>%
  mutate(SERVICE_DATE = as.Date(SERVICE_DATE)) %>%
  pivot_longer(cols = c(BASELINE, SCENARIO),
               names_to = "Dataset",
               values_to = "Utilization")


ggplot(total_utilization, aes(x = SERVICE_DATE, y = Utilization, color = Dataset)) +
  geom_smooth(method = "loess", se = FALSE, span = 0.08, linewidth = 1.2) +
  facet_wrap(~ FACILITY_MSX) +
  scale_y_continuous(labels = scales::percent) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_color_manual(values = mshs_colors) + 
  labs(title = "Utilization Over Time by Hospital",
       x = "Service Date",
       y = "Utilization",
       color = "Dataset") +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        strip.text = element_text(size = 14, face = "bold"))
```

## Baseline vs. Scenario IP Utilization
```{r baseline vs. scenario}

# get list of service groups effected by scenario
service_change <- ip_comparison_total %>%
  filter(AVG_UTILIZATION_BASELINE != AVG_UTILIZATION_SCENARIO) %>%
  ungroup() %>%
  distinct(SERVICE_GROUP) %>%
  pull()

# prep data from graph
results_long <- ip_comparison_monthly %>%
  filter(SERVICE_GROUP %in% service_change) %>%
  pivot_longer(
    cols = c(AVG_UTILIZATION_BASELINE, AVG_UTILIZATION_SCENARIO),
    names_to = "Scenario",
    values_to = "Utilization") %>%
  mutate(
    SERVICE_MONTH = as.Date(SERVICE_MONTH),
    Scenario = case_when(
      Scenario == "AVG_UTILIZATION_BASELINE" ~ "Baseline",
      Scenario == "AVG_UTILIZATION_SCENARIO" ~ "Scenario"),
    Utilization = case_when(
      Scenario == "Scenario" & is.na(Utilization) ~ 1,
      TRUE ~ Utilization))

# Plot
ggplot(results_long, aes(x = SERVICE_MONTH, y = Utilization, fill = Scenario)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_hline(yintercept = .95, color = "black", linetype = "solid", linewidth = 0.7) +
  scale_y_continuous(limits = c(0, 1.5), labels = scales::percent) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_fill_manual(values = mshs_colors) + 
  facet_grid(FACILITY_MSX ~ SERVICE_GROUP) +
  labs(title = "Inpatient Utilization Comparison",
       x = "Service Month",
       y = "Utilization",
       fill = "Scenario") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
        strip.text = element_text(face = "bold"))
```

## Daily Scenario IP Utilization
```{r scenario utilization}

# Plot
ggplot(ip_comparison_daily %>%
         mutate(SERVICE_DATE = as.Date(SERVICE_DATE)), 
       aes(x = SERVICE_DATE,
           y = UTILIZATION_SCENARIO,
           color = SERVICE_GROUP,
           group = SERVICE_GROUP)
       ) +
geom_smooth(se = FALSE, method = "loess", span = 0.1, linewidth = 1.2) +
geom_hline(yintercept = 0.95, color = "black", linewidth = 1.2) +
facet_wrap(~ FACILITY_MSX) +
scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 1.3)) +
scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
scale_color_manual(name = "Service Group", values = mshs_colors) +   
labs(
  title = "Daily Utilization (Scenario)",
  x = "Service Date",
  y = "Utilization (Scenario)"
) +
theme_minimal() +
theme(
  legend.position = "bottom",
  plot.title = element_text(hjust = 0.5),
  axis.text.x = element_text(angle = 45, hjust = 1),
  strip.text = element_text(face = "bold"),
  panel.border = element_rect(color = "black", fill = NA)
)
```