---
title: "model-lab-rad"
output: html_document
date: "`r Sys.Date()`"
---

# Read Processing
```{r dataset list}
library(DBI)
library(odbc)
library(glue)
library(lubridate)
library(dplyr) 
library(ggplot2)
conn <- dbConnect(odbc(), "OAO Cloud DB Production")
query <- glue("SELECT PRIM_ENC_CSN_ID, SERVICE_DATE, TX_POST_DATE FROM OE_CHARGE_DETAIL
WHERE BILLING_CAT_DESC = 'BED CHARGES' AND TO_DATE(SERVICE_DATE, 'YYYYMMDD') >= DATE '2024-06-01'
              ")
OUTPUT <- dbGetQuery(conn, query)
dbDisconnect(conn)
```


```{r dataset list}
OUTPUT <- OUTPUT %>%
  mutate(
    SERVICE_DATE   = ymd(SERVICE_DATE),
    TX_POST_DATE   = ymd(TX_POST_DATE),
    DIFFERENCE     = as.numeric(difftime(TX_POST_DATE, SERVICE_DATE, units = "days")),
    SERVICE_MONTH  = format(SERVICE_DATE, "%m"),
    SERVICE_YEAR   = format(SERVICE_DATE, "%Y"),
    SERVICE_WEEK   = week(SERVICE_DATE),
    MONTHLY_DIFFERENCE = (DIFFERENCE %/% 30) + 1

  )

CUMULATIVE_PERCENT_OUTPUT <- OUTPUT %>%
  count(MONTHLY_DIFFERENCE) %>%
  arrange(MONTHLY_DIFFERENCE) %>%
  mutate(
    CUM_COUNT = cumsum(n),
    TOTAL = sum(n),
    CUM_PERCENT = (CUM_COUNT / TOTAL) * 100
  )

CUMULATIVE_PERCENT_TABLE <- CUMULATIVE_PERCENT_OUTPUT %>%
  arrange(MONTHLY_DIFFERENCE) %>%
  mutate(
    PERCENTAGE = n / sum(n) * 100,
    CUMULATIVE_PERCENTAGE = cumsum(PERCENTAGE)
  ) %>%
  select(MONTHLY_DIFFERENCE, PERCENTAGE, CUMULATIVE_PERCENTAGE)
```


```{r dataset list}
ggplot(CUMULATIVE_PERCENT_OUTPUT, aes(x = factor(MONTHLY_DIFFERENCE), y = CUM_PERCENT)) +
  geom_col(fill = "#00AEFF", alpha = 0.7, color = "black", width = 0.6) +
  geom_text(
    aes(label = paste0(floor(CUM_PERCENT * 100) / 100, "%")),
    vjust = -0.5, size = 2.3
  ) +
  labs(
    x = "Monthly Difference",
    y = "Cumulative Percentage",
    title = "Cumulative Percentage by Months Difference"
  ) +
  theme_minimal()

```