insert into IPCAP_BEDCHARGE_CARETEAM
with bedcharge as (
    select ipbc.*,
           TO_DATE(ipbc.SERVICE_DATE || ' 23:59:59', 'YYYYMMDD HH24:MI:SS') as SERVICE_DATE_MIDNIGHT
    from IPCAP_BEDCHARGES ipbc
), careteam as (
    select *
    from IPCAP_CARE_TEAM
), joined as (
    select bc.ENCOUNTER_NO, bc.MSMRN, bc.FACILITY_MSX, bc.DSCH_DT_SRC, bc.DSCH_TIME_SRC, bc.ADMIT_DT_SRC, bc.ADMIT_TIME_SRC, bc.LOS_NO_SRC, bc.UNIT_DESC_MSX, bc.ATTENDING_MD_CD_SRC, bc.ATTENDING_MD_NAME_MSX, bc.ATTENDING_VERITY_DEPT_CD, bc.ATTENDING_VERITY_DEPT_DESC, bc.ATTENDING_VERITY_DIV_CD, bc.ATTENDING_VERITY_DIV_DESC, bc.ATTENDING_VERITY_REPORT_SERVICE, bc.PRINCIPAL_SURGEON_CD_SRC, bc.PRINCIPAL_SURGEON_NAME_MSX, bc.PRINCIPAL_SURGEON_VERITY_DEPT_DESC, bc.PRINCIPAL_SURGEON_VERITY_DIV_DESC, bc.MSDRG_CD_SRC, bc.MSDRG_DESC_MSX, bc.ADMIT_TYPE_CD_SRC, bc.ADMIT_TYPE_DESC_SRC, bc.VIZ_EX_LOS, bc.SERVICE_DESC_MSX, bc.FACILITY_ABBR, bc.COST_CENTER_C, bc.EPIC_DEPT_ID, bc.EPIC_DEPT_NAME, bc.SERVICE_DATE, bc.SERVICE_DATE_MIDNIGHT, bc.QUANTITY, bc.CPT_HCPCS_C, bc.CPT_COUNT, bc.LAB_COUNT, bc.DESCRIPTION_SHORT, bc.BILLING_CAT_C, bc.BILLING_CAT_DESC, bc.CATEGORY, bc.RPT_GRP_NINETEEN_C, bc.RPT_GRP_NINETEEN_DESC, bc.NEW_COST_CENTER_C, bc.NEW_GL_COMPONENT, bc.EXTERNAL_NAME, bc.SERVICE_GROUP, bc.LOC_NAME,
           ct.NPI,
           ct.PROVIDERID,
           ct.MD_PROV_NM,
           ct.ATTEND_FROM_DTTM,
           ct.ATTEND_TO_DTTM,
           ct.PROV_TYPE,
           ct.VERITY_DEPT_1_CD_SRC,
           ct.VERITY_DEPT_1_DESC_SRC,
           ct.VERITY_DIV_DESC_SRC
    from bedcharge bc
    left join careteam ct on
        bc.ENCOUNTER_NO = ct.ENCOUNTER_NO AND
        bc.SERVICE_DATE_MIDNIGHT between ct.ATTEND_FROM_DTTM and ct.ATTEND_TO_DTTM
)
select
    ENCOUNTER_NO, MSMRN, FACILITY_MSX, DSCH_DT_SRC, DSCH_TIME_SRC, ADMIT_DT_SRC, ADMIT_TIME_SRC, LOS_NO_SRC, UNIT_DESC_MSX, ATTENDING_MD_CD_SRC, ATTENDING_MD_NAME_MSX, ATTENDING_VERITY_DEPT_CD, ATTENDING_VERITY_DEPT_DESC, ATTENDING_VERITY_DIV_CD, ATTENDING_VERITY_DIV_DESC, ATTENDING_VERITY_REPORT_SERVICE, PRINCIPAL_SURGEON_CD_SRC, PRINCIPAL_SURGEON_NAME_MSX, PRINCIPAL_SURGEON_VERITY_DEPT_DESC, PRINCIPAL_SURGEON_VERITY_DIV_DESC, MSDRG_CD_SRC, MSDRG_DESC_MSX, ADMIT_TYPE_CD_SRC, ADMIT_TYPE_DESC_SRC, VIZ_EX_LOS, SERVICE_DESC_MSX, FACILITY_ABBR, COST_CENTER_C, EPIC_DEPT_ID, EPIC_DEPT_NAME, SERVICE_DATE, SERVICE_DATE_MIDNIGHT, CPT_HCPCS_C, CPT_COUNT, LAB_COUNT, DESCRIPTION_SHORT, BILLING_CAT_C, BILLING_CAT_DESC, CATEGORY, RPT_GRP_NINETEEN_C, RPT_GRP_NINETEEN_DESC, NEW_COST_CENTER_C, NEW_GL_COMPONENT, EXTERNAL_NAME, SERVICE_GROUP, LOC_NAME,
    NPI,
    PROVIDERID,
    MD_PROV_NM,
    ATTEND_FROM_DTTM,
    ATTEND_TO_DTTM,
    PROV_TYPE,
    VERITY_DEPT_1_CD_SRC,
    VERITY_DEPT_1_DESC_SRC,
    VERITY_DIV_DESC_SRC,
    CASE
        WHEN SUM(QUANTITY) > 1 THEN 1
        ELSE SUM(QUANTITY)
    END as QUANTITY
from joined
group by
    ENCOUNTER_NO, MSMRN, FACILITY_MSX, DSCH_DT_SRC, DSCH_TIME_SRC, ADMIT_DT_SRC, ADMIT_TIME_SRC, LOS_NO_SRC, UNIT_DESC_MSX, ATTENDING_MD_CD_SRC, ATTENDING_MD_NAME_MSX, ATTENDING_VERITY_DEPT_CD, ATTENDING_VERITY_DEPT_DESC, ATTENDING_VERITY_DIV_CD, ATTENDING_VERITY_DIV_DESC, ATTENDING_VERITY_REPORT_SERVICE, PRINCIPAL_SURGEON_CD_SRC, PRINCIPAL_SURGEON_NAME_MSX, PRINCIPAL_SURGEON_VERITY_DEPT_DESC, PRINCIPAL_SURGEON_VERITY_DIV_DESC, MSDRG_CD_SRC, MSDRG_DESC_MSX, ADMIT_TYPE_CD_SRC, ADMIT_TYPE_DESC_SRC, VIZ_EX_LOS, SERVICE_DESC_MSX, FACILITY_ABBR, COST_CENTER_C, EPIC_DEPT_ID, EPIC_DEPT_NAME, SERVICE_DATE, SERVICE_DATE_MIDNIGHT, CPT_HCPCS_C, CPT_COUNT, LAB_COUNT, DESCRIPTION_SHORT, BILLING_CAT_C, BILLING_CAT_DESC, CATEGORY, RPT_GRP_NINETEEN_C, RPT_GRP_NINETEEN_DESC, NEW_COST_CENTER_C, NEW_GL_COMPONENT, EXTERNAL_NAME, SERVICE_GROUP, LOC_NAME,
    NPI,
    PROVIDERID,
    MD_PROV_NM,
    ATTEND_FROM_DTTM,
    ATTEND_TO_DTTM,
    PROV_TYPE,
    VERITY_DEPT_1_CD_SRC,
    VERITY_DEPT_1_DESC_SRC,
    VERITY_DIV_DESC_SRC
ORDER BY ENCOUNTER_NO, SERVICE_DATE_MIDNIGHT;